wandb_version: 1

T_0:
  desc: null
  value: 25
T_max:
  desc: null
  value: 3000050
_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.10.8
    start_time: 1678817933.467215
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      - 80
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      - 80
      3:
      - 1
      - 13
      - 16
      - 23
      4: 3.10.8
      5: 0.13.11
      8:
      - 1
      - 2
      - 4
      - 5
base_model:
  desc: null
  value: None
bidirectional:
  desc: null
  value: 0
comment:
  desc: null
  value: model-pix2pix-rnn-aqi|latent_size-128|info_channels-1|hidden_dim-512|num_layers-2|bidirectional-0|dim-224x224
device:
  desc: null
  value: cpu
epochs:
  desc: null
  value: 100
exp_name:
  desc: null
  value: nasscom-taim
hidden_size:
  desc: null
  value: 512
image_size:
  desc: null
  value:
  - 224
  - 224
in_channels:
  desc: null
  value: 1
latent_size:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.0003
min_lr:
  desc: null
  value: 1.0e-06
model_name:
  desc: null
  value: pix2pix-rnn-aqi
n_accumulate:
  desc: null
  value: 32
n_fold:
  desc: null
  value: 5
num_classes:
  desc: null
  value: 3
num_layers:
  desc: null
  value: 2
scheduler:
  desc: null
  value: CosineAnnealingLR
seed:
  desc: null
  value: 42
train_bs:
  desc: null
  value: 1
trial_num:
  desc: null
  value: 1
valid_bs:
  desc: null
  value: 1
warmup_epochs:
  desc: null
  value: 0
wd:
  desc: null
  value: 1.0e-06
